New plugin for dumping .torrent info
Novik/ruTorrent pull request #2650
Opened 2024-04-15 07:33 UTC by TheGoblinHero

Regularly I need to export info about torrent (all filenames, exact size in bytes, etc) to the text format. So I wrote a simple plugin:
![dump](https://github.com/Novik/ruTorrent/assets/12325495/aada60e3-c32b-4023-bb5b-aef376d77c8b)
The plugin uses external tool to dump the torrent. Personally I use [old dumptorrent utility with several patches](https://github.com/TheGoblinHero/dumptorrent), but it's configurable, so you can use any utility you want.

2024-04-15 10:45 UTC, stickz requested changes
Please submit to `develop` branch instead of `master`. We will release with `ruTorrent v4.4`. The wiki also as public permissions to edit. You can add this plugin in there.

2024-04-15 10:45 UTC, stickz commented on plugins/dump/plugin.info
> +plugin.dependencies: _task
Please add an external error for `dumptorrent`.
```
rtorrent.external.error: dumptorrent
```

2024-04-15 10:45 UTC, stickz commented on plugins/dump/lang/ru.js
> +thePlugins.get("dump").langLoaded();
Please add new line at end of file.

2024-04-15 10:45 UTC, stickz commented on plugins/dump/lang/en.js
> +thePlugins.get("dump").langLoaded();
Please add new line at end of file.

2024-04-15 10:45 UTC, stickz commented on plugins/dump/conf.php
> +$arguments = "-v";			// Program arguments
Please add new line at end of file.

2024-04-15 10:45 UTC, stickz commented on plugins/dump/conf.php
> +
Please add a comment here, where we can find the external dependency required.

2024-04-15 11:46 UTC, TheGoblinHero commented
Fixed. [Wiki page is added](https://github.com/Novik/ruTorrent/wiki/PluginDump). Should I create another PR to submit to develop?

2024-04-15 12:02 UTC, stickz commented
LGTM! Thanks!

2024-04-15 12:02 UTC, merged

2024-11-18 19:49 UTC, buggsi commented
Useful plugin, I started testing v5.1beta and the plugin is included.

2024-11-23 21:43 UTC, jegue commented
if  dumptorrent not installed 
follow this

sudo apt-get install gcc make
wget "from github source"
tar -xvf dumptorrent-1.x.tar.gz
cd dumptorrent-1.x
make
sudo cp dumptorrent /usr/local/bin