added a copy button to console log window
Novik/ruTorrent pull request #2666
Opened 2024-05-29 10:49 UTC by jevenski

Added a copy button to console window, making copying console log like mediainfo result a little bit more confortable, without having to select the entire text and hit Ctrl+C. Log a message and nothing else when the console log is empty, e.g. when screenshots are being generated.

![console_log](https://github.com/Novik/ruTorrent/assets/26022962/f6d4e538-068a-4caf-a0f7-71654a0f29d0)

PS: Apologies again for all the mess by creating pull requests again and again... I made some adjustments with my fork and closed the old request accidentally. Now I'm getting a hang of the git philosophy.

2024-06-03 14:55 UTC, stickz requested changes
Looks good, just need to adjust spacing and resolve review.

2024-06-03 14:55 UTC, stickz commented on plugins/_task/init.js
> +
Can you adjust the spacing to match the other items in the Javascript file?

2024-06-03 14:55 UTC, stickz commented on plugins/_task/init.js
> +	plugin.background[ plugin.foreground.no ] = cloneObject( this.foreground );
Formatting.

2024-06-03 14:55 UTC, stickz commented on plugins/_task/init.js
> +      "<input type='button' id='tskCopy' class='Button' value='"+theUILang.tskCopy+"'/>"+
Formatting.

2024-06-03 14:55 UTC, stickz commented on plugins/_task/init.js
> +  $("#tskCopy").on('click', plugin.copyConsoleLog);
Formatting.

2024-06-09 11:24 UTC, jevenski commented
Submitted another commit regarding the indent format changes.

2024-06-09 14:15 UTC, merged

2024-08-12 20:10 UTC, koblack commented
Copy from mediainfo and unpack plugins throw an error
```
webui.js?v=430:2482 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText') from TypeError: Cannot read properties of undefined (reading 'writeText')
    at plugin.copyConsoleLog (<anonymous>:131:23)
    at HTMLInputElement.dispatch (http://xxx/ruTorrent-develop/js/jquery.js?v=430:2:40035)
    at v.handle (http://xxx/ruTorrent-develop/js/jquery.js?v=430:2:38006)
```