Apply grid layout to Ratio Rules dialog
Novik/ruTorrent pull request #2684
Opened 2024-06-28 14:38 UTC by jevenski

Applied Bootstrap grid layout to the Ratio Rules dialog, as well as added two quick keyboard shortcuts for moving rules up and down in the list.

1. `md` screens and larger
![Screenshot 2024-06-28 223503](https://github.com/Novik/ruTorrent/assets/26022962/2f5a84a7-8601-4958-a749-e1589b8ad199)

2. Smaller screens
![Screenshot 2024-06-28 223528](https://github.com/Novik/ruTorrent/assets/26022962/8c9030c8-4bd4-452c-a11c-f559553ff6a6)

2024-06-28 17:04 UTC, stickz requested changes

2024-06-28 17:04 UTC, stickz commented on plugins/extratio/extratio.css
> +}
I fixed some style issues with buttons list. Please update `extratio.css` accordingly.  See https://github.com/Novik/ruTorrent/commit/bed2f021213f14e2e8790a35ffd55b46d3fc6cbc

2024-06-28 17:13 UTC, stickz commented
@jevenski I have a high priority task for you - if you're interested. We need to remove the throttle dependency for `extratio` and make it optional. Over 100k instances of ruTorrent have `extratio` disabled because it requires `throttle`. Throttle limits max speed to approximately 1.6gbps in both directions due to a limitation with rTorrent. 

https://github.com/Novik/ruTorrent/blob/9bf6e15c4864a71ff9e9ca5ea689fd001931279b/plugins/extratio/plugin.info#L5

We can check if the `throttle` plugin is loaded. Then adjust our GUI and xmlrpc queries accordingly.

2024-06-29 00:31 UTC, jevenski commented
That's interesting. I didn't notice that. So from what I understand, we can do a dependency check on the `throttle` plugin as the first step. If the check returns `True`, it just flows as the old way. And if it returns `False`, we disable the `set throttle to` part of the rule setting.

As for the xmlrpc queries, we just remove the channel from the query strings. No adjustments in php scripts are needed. Is that correct?

```javascript
rTorrentStub.prototype.setratiorules = function()
{
	this.content = "mode=setrules";
	plugin.storeRuleParams();
	for(var i=0; i<plugin.rules.length; i++)
	{
		var rle = plugin.rules[i];
		var enabled = $("#_rre"+i).prop("checked") ? 1 : 0;
		var name = $("#_rrn"+i).val();
		this.content = this.content+"&name="+encodeURIComponent(name)+"&pattern="+encodeURIComponent(rle.pattern)+"&enabled="+enabled+
		        "&reason="+rle.reason+
			"&channel="+rle.channel+"&ratio="+rle.ratio+
			"&no="+rle.no;
	}
	this.contentType = "application/x-www-form-urlencoded";
	this.mountPoint = "plugins/extratio/action.php";
	this.dataType = "json";
}
```

2024-06-29 01:42 UTC, stickz commented
Great job @jevenski. I'll merge this now. And yes it looks like you're right about the `xmlrpc` queries!

2024-06-29 01:42 UTC, merged