Flex stable
Novik/ruTorrent pull request #2700
Opened 2024-07-29 03:39 UTC by jevenski

These small tweaks are meant to simplify the dimension control mechanism of `S-Table`s, as a preparation before rewriting the main-content part of the WebUI.

2024-07-29 03:43 UTC, jevenski commented on css/stable.css
> +  display: flex;
Set to `flex` display for a smoother layout.

2024-07-31 17:45 UTC, stickz commented
I found two disk space icons on the Material Design and Oblivion themes on the status bar. I'm not sure if it was caused by this pull request. Ether way, could we address the regression here?

2024-08-01 01:14 UTC, jevenski commented
The issues were introduced when changing the status bar for responsiveness. The fixes are committed in this PR now.

2024-08-01 20:07 UTC, stickz commented
> The issues were introduced when changing the status bar for responsiveness. The fixes are committed in this PR now.

The check boxes are overlapping in the settings menu on the `Blue` theme. Could this PR resolve that problem as well?

2024-08-02 07:19 UTC, jevenski commented
> The check boxes are overlapping in the settings menu on the `Blue` theme. Could this PR resolve that problem as well?

That's one of the reasons why I wanted to remove some of the themes. The Blue theme has this `jquery.checkbox.js` plugin that alters the styles of checkboxes, by replacing the original checkboxes with images of checkboxes. The comments in the beginning of the file says the plugin was copyrighted back in 2008, which was 16 years ago. The link provided by the author cannot be reached now, and there's not much documentation in the files themselves, so I don't have a clear clue what this plugin was intended for exactly.

Apart from that, the theme's `init.js` alters the DOM of dialog windows a lot. These changes make this plugin hard to maintain, costing too much time for just one single plugin.

2024-08-03 17:18 UTC, stickz commented
> > The check boxes are overlapping in the settings menu on the `Blue` theme. Could this PR resolve that problem as well?
> 
> That's one of the reasons why I wanted to remove some of the themes. The Blue theme has this `jquery.checkbox.js` plugin that alters the styles of checkboxes, by replacing the original checkboxes with images of checkboxes. 

I don't like this theme feature. Can we remove `jquery.checkbox.js` and use restyled regular checkboxes to make the theme easier to maintain? Do you think this is a better option than removing the theme entirely?

2024-08-04 01:18 UTC, jevenski commented
> I don't like this theme feature. Can we remove `jquery.checkbox.js` and use restyled regular checkboxes to make the theme easier to maintain? Do you think this is a better option than removing the theme entirely?

Yeah, personally I think themes like Blue and Acid look old-fashioned. We can remove these additional features like `jquery.checkbox.js` and make it simpler. In the long run, maybe we can open a poll for our users to vote?

2024-08-04 12:35 UTC, stickz commented
I don't miss the query checkboxes at all for the Blue theme. I think the default ones look better. That problem is resolved.

**I found one more issue in Settings->Download->Check hash after download.**

![check_hash_issue](https://github.com/user-attachments/assets/cc53d1bb-c16f-41b5-969b-f34861d58fec)

2024-08-08 16:37 UTC, stickz requested changes
Please remove all instances of `plugin.correctCheckboxes` since the function was removed. It is outputting JavaScript errors.

`Uncaught TypeError: plugin.correctCheckboxes is not a function from TypeError: plugin.correctCheckboxes is not a function`

2024-08-08 16:37 UTC, stickz commented on plugins/theme/themes/Blue/init.js
> +			plugin.correctCheckboxes();
Not a function

2024-08-08 16:37 UTC, stickz commented on plugins/theme/themes/Blue/init.js
> +			plugin.correctCheckboxes();
Not a function.

2024-08-08 16:37 UTC, stickz commented on plugins/theme/themes/Blue/init.js
> +			plugin.correctCheckboxes();
Not a function.

2024-08-08 16:37 UTC, stickz commented on plugins/theme/themes/Blue/init.js
> +			plugin.correctCheckboxes();
Not a function.

2024-08-08 16:37 UTC, stickz commented on plugins/theme/themes/Blue/init.js
> +			plugin.correctCheckboxes();
Not a function.

2024-08-11 11:32 UTC, stickz commented
Thanks for the all the bug fixes!

2024-08-11 11:32 UTC, merged