Use flex layout on context menu items
Novik/ruTorrent pull request #2812
Opened 2024-12-01 15:36 UTC by jevenski

This patch does modifications to the context menu. After this patch is merged, the search menu on the top navbar can be more easily replaced with the bootstrap dropdown menu implementation, just like the plugins dropdown menu.

### Commit Message
- Split menu-item selection and sub-menu expansion icons from the background image, and use pseudo-elements for them.
- Use CSS variables on menu background and font color. This simplifies theme adaption process and reduces code duplication.
- Use inline base64 string for menu selection and expansion icons, replacing previous image urls. This saves a few requests for images and enhances performance by reducing load time.

2024-12-01 17:01 UTC, stickz requested changes
Remove `Details...` from `CMenu` in this pull request. This is useless because it simply links to the `General` tab bellow. The user can display this tab in 1 click instead of 2 clicks.

2024-12-01 20:07 UTC, koblack commented
1. The separation line is not centered
![image](https://github.com/user-attachments/assets/9a6d3297-f7d2-4c37-bca2-461f5e06a72a)

2. Too much space between menu and submenu
![image](https://github.com/user-attachments/assets/0835a5e6-82d4-47f0-8236-640b1542ad68)
![image](https://github.com/user-attachments/assets/d6250a41-3ac4-463e-b5d1-bc840aa9c240)
![image](https://github.com/user-attachments/assets/8a759970-8907-4c7d-8580-5bb3e8a65aeb)

2024-12-02 05:42 UTC, jevenski commented on css/style.css
> +  padding: 0;
![20241202134001](https://github.com/user-attachments/assets/6e7182b8-c6d4-4525-874b-8954c1a4b7e3)
Above is a screenshot of `.CMenu` with `padding: 0.25rem 1rem;`. I think `padding: 0;` looks better. Plus, the menu item links have a padding of 0.25rem on them, so the texts won't collide with the menu edge.

2024-12-02 06:29 UTC, jevenski commented on css/style.css
>  ul.CMenu li:hover ul {display: block; position: absolute; top: 0; left: 146px; width:150px;}
The submenu left offset will need to be set dynamically using JavaScript to address @koblack 's feedback.

2024-12-02 14:45 UTC, stickz commented
@jevenski Looks good, thanks! Merged. I added 0.25rem top and bottom padding to the CMenu. The text was too close to the edge when testing. I didn't add any left and right padding, as there is already padding for that.

2024-12-02 14:45 UTC, merged