Create s-table rows using jQuery DOM manipulation
Novik/ruTorrent pull request #2821
Opened 2024-12-10 01:58 UTC by jevenski

- Adjust s-table's `createRow()` method to use jQuery to create table rows. This is more readable than generating table rows with HTML strings.

2024-12-10 01:59 UTC, jevenski commented on css/style.css
> -.stable-icon {background-image: url(../images/tstatus.png); background-repeat: no-repeat}
Move to `stable.css`

2024-12-10 02:00 UTC, jevenski commented on js/stable.js
> +	row.find("td:first-child div").prepend(this.createIcon(icon));
Append an icon to the first cell in a row directly, without having to check for the cell index on every cell.

2024-12-10 02:02 UTC, jevenski commented on js/stable.js
> -					ind === 0 ? this.createIconHTML(icon) : ''
This conditional runs on every cell. If there are 25 cells in a row, and 1,000 rows in a table, there will be 24 * 1,000 = 240,000 ineffective checks.

2024-12-10 02:03 UTC, jevenski commented on js/stable.js
> +	noty("Deprecation warning: `dxSTable.createIconHTML()` is deprecated. Please use `dxSTable.createIcon()` instead.");
Add a deprecation warning to prevent sudden API breakage.

2024-12-10 02:10 UTC, jevenski commented on js/stable.js
> -					ind === 0 ? this.createIconHTML(icon) : ''
This conditional runs on every cell. If there are 25 cells in a row, and 1,000 rows in a table, there will be 24 * 1,000 = 24,000 ineffective checks.

2024-12-10 02:14 UTC, jevenski commented on plugins/theme/themes/DarkBetter/style.css
> +    background-image: url(./images/tb_rss_group.svg);
Typo fix.

2024-12-10 02:14 UTC, jevenski commented on plugins/theme/themes/DarkBetter/style.css
> -    background-image: url(./images/dir.svg);
Dedupe.

2024-12-10 02:21 UTC, jevenski commented on plugins/theme/themes/DarkBetter/style.css
> -    background-image: url(./images/green.svg);
Dedupe.

2024-12-10 16:45 UTC, stickz requested changes

2024-12-10 16:45 UTC, stickz commented on js/stable.js
> +	if (!browser.isIE7x) {
You can remove this check. It's not required anymore.

2024-12-12 18:12 UTC, stickz commented
The text is too close to the icon for the torrent name. Please increase spacing to match `v5.1`.

2024-12-16 01:59 UTC, stickz commented
@jevenski I rebased this for you. Great job with the performance improvements.

However, when I resize a column the header and body goes out of sync. This critical issue needs fixed before I can merge.

2024-12-16 05:24 UTC, jevenski commented
@stickz  I did some modification to this patch and force pushed again. Previous changes are all squashed into one commit. Additionally, an old s-table method (`.calcSize()`) is removed and marked for deprecation to unify APP behaviors on different browsers and sync cell width between s-table header and body.

2024-12-16 05:36 UTC, stickz commented
All fixed, great job!

2024-12-16 05:36 UTC, merged